services:
  evochora:
    volumes:
      # Mountet die local.conf zusätzlich in den Container (neben der evochora.conf)
      - ./local.conf:/home/appuser/app/config/local.conf:ro
    
    # Überschreibt den Start-Befehl, um die local.conf zu nutzen
    command: ["bin/evochora", "--config", "config/local.conf", "node", "run"]
